package com.wellness.model;

public enum NotificationType {
    COUNSELING_REQUEST,
    REQUEST_ACCEPTED,
    REQUEST_REJECTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    NEW_CHAT_MESSAGE,
    ASSESSMENT_REMINDER,
    NEW_RESOURCE,
    COUNSELOR_FOLLOW_UP,
    ADMIN_ANNOUNCEMENT
}
